"""empty message

Revision ID: be3e3bdcb87e
Revises: 089fa544ceb0
Create Date: 2020-03-26 22:44:24.801644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be3e3bdcb87e'
down_revision = '089fa544ceb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER', 'image')
    op.add_column('details', sa.Column('image', sa.String(length=600), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('details', 'image')
    op.add_column('USER', sa.Column('image', mysql.VARCHAR(length=600), nullable=False))
    # ### end Alembic commands ###
